theme: jekyll-theme-slate
title: Interactive Data Visualization
description: Welcome to my site to host interactive plots for my research into the correlation between single cell mechanics and gene expression! <br><br>This work was a part of my PhD thesis at Georgia Tech and Emory University in the lab of <a href="http://www.sulchek2.gatech.edu">Dr. Todd Sulchek</a>. - Katie Young
