theme: jekyll-theme-slate
title: Interactive Data Visualization
description: Welcome to my site to host interactive plots for my research into the correlation between single cell mechanics and gene expression! I am a PhD candidate at Georgia Tech and Emory University in the lab of Dr. Todd Sulchek. - Katie Young
